# Generated by Django 5.2.1 on 2025-08-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
